export const ActionTypes = {
    SET_SITES: 'SET_SITES',
    SELECTED_SITE: 'SELECTED_SITE',
    REMOVE_SELECTED_SITE: 'REMOVE_SELECTED_SITE',
    SET_ARTICLES: 'SET_ARTICLES',
    SET_FAVORITE_ARTICLES: 'SET_FAVORITE_ARTICLES',
    SET_USER: 'SET_USER',
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_NAME: 'SET_NAME',
};